import test from 'node:test';import assert from 'node:assert/strict';import * as THREE from 'three';
import {posedAndroid,prismGuide} from '../src/lib/cyber/reference-layout.js';
import {worldSocket,routeSockets} from '../src/lib/assembly-sockets.js';
import {inspect,dispose} from '../src/lib/modeling.js';
test('gesture, masses and assembly share the same pose guide, rather than separate hand-matched poses',()=>{const roots=['gesture','masses','assembly'].map(stage=>posedAndroid({stage,detail:'draft',cables:false}));try{assert.deepEqual(roots[0].userData.poseGuide.anchors,roots[2].userData.poseGuide.anchors);assert.deepEqual(roots[1].userData.poseGuide.anchors,roots[2].userData.poseGuide.anchors);assert.ok(inspect(roots[0]).triangles<inspect(roots[2]).triangles*.1);assert.ok(inspect(roots[2]).triangles<600000);}finally{roots.forEach(dispose);}});
test('independent depth hypotheses remain spatial; calibration and old inputs are not mutated',()=>{const a=prismGuide(),b=prismGuide({overrides:{wristNear:{depth:-.6}}});assert.notDeepEqual(a.point('wristNear'),b.point('wristNear'));assert.deepEqual(a.point('head'),b.point('head'));assert.ok(Math.abs(a.point('shoulderNear')[2]-a.point('shoulderFar')[2])>.2);});
test('socket lead directions and end points follow transformed assembly owners',()=>{const p=new THREE.Group(),q=new THREE.Group();p.position.set(.2,.3,0);q.position.set(1,1,.1);p.rotation.y=.6;p.updateMatrixWorld();const a=worldSocket(p,{at:[0,0,.02]}),b=worldSocket(q);const route=routeSockets(a,b,{via:[[.5,.8,.5]],lead:.04});assert.deepEqual(route[0],a.position);assert.deepEqual(route.at(-1),b.position);assert.ok(new THREE.Vector3(...route[1]).sub(new THREE.Vector3(...route[0])).normalize().distanceTo(new THREE.Vector3(...a.direction))<1e-9);assert.throws(()=>routeSockets(a,b,{lead:0}));});
test('both soles sit on the deck plane after pose mounting',()=>{const root=posedAndroid({detail:'draft',cables:false});try{root.updateMatrixWorld(true);const soles=[];root.traverse(o=>{if(o.name==='Orange sole'){o.geometry.computeBoundingBox();const box=o.geometry.boundingBox.clone().applyMatrix4(o.matrixWorld);soles.push(box.min.y);}});assert.equal(soles.length,2);soles.forEach(y=>assert.ok(Math.abs(y-.155)<.002,y));}finally{dispose(root);}});
test('left and right arm and leg lengths agree after ray-constrained depth selection',()=>{const g=prismGuide();for(const [a,b,len]of[['shoulder','elbow',.25],['elbow','wrist',.30],['hip','knee',.43],['knee','ankle',.45]])for(const side of['Near','Far'])assert.ok(Math.abs(new THREE.Vector3(...g.point(a+side)).distanceTo(new THREE.Vector3(...g.point(b+side)))-len)<1e-8);});
