"""Read public tutorial metadata/captions, without login, video downloads or retries.

The manifest is explicit and bounded. A failed fetch stays a failed observation;
metadata or caption access is never labeled as watching the video.
"""
from __future__ import annotations
import argparse
import json
import re
from pathlib import Path
from urllib.parse import urlparse, parse_qs, urlencode
from urllib.request import Request, build_opener, HTTPRedirectHandler

HOSTS = {"www.youtube.com", "youtube.com", "m.youtube.com"}
VIDEO_ID = re.compile(r"^[A-Za-z0-9_-]{11}$")
LIMIT = 4 * 1024 * 1024


def video_id(url: str) -> str:
    p = urlparse(url)
    if p.scheme != "https" or p.hostname not in HOSTS or p.path != "/watch" or p.username or p.password or p.port:
        raise ValueError("Use an HTTPS youtube.com/watch URL without credentials or port")
    values = parse_qs(p.query).get("v", [])
    if len(values) != 1 or not VIDEO_ID.fullmatch(values[0]):
        raise ValueError("Expected exactly one valid YouTube video ID")
    return values[0]


def safe_url(url: str) -> None:
    p = urlparse(url)
    if p.scheme != "https" or p.hostname not in HOSTS or p.username or p.password or p.port:
        raise ValueError("Fetch or redirect outside the public YouTube HTTPS allowlist")


class SameProviderRedirect(HTTPRedirectHandler):
    def redirect_request(self, req, fp, code, msg, headers, newurl):
        safe_url(newurl)
        return super().redirect_request(req, fp, code, msg, headers, newurl)


def fetch(url: str) -> str:
    safe_url(url)
    request = Request(url, headers={"User-Agent": "3DWorkshop-ReferenceReader/1.0", "Accept-Language": "en"})
    with build_opener(SameProviderRedirect()).open(request, timeout=12) as response:
        safe_url(response.url)
        data = response.read(LIMIT + 1)
        if len(data) > LIMIT:
            raise ValueError("Reference response exceeds 4 MiB budget")
        return data.decode("utf-8")


def player_json(html: str) -> dict:
    decoder = json.JSONDecoder()
    for match in re.finditer(r'(?:var\s+)?ytInitialPlayerResponse\s*=\s*', html):
        try:
            result, _ = decoder.raw_decode(html[match.end():])
            if isinstance(result, dict):
                return result
        except json.JSONDecodeError:
            pass
    raise ValueError("Public player metadata not present in response")


def captions_json(text: str) -> list[dict]:
    payload = json.loads(text)
    result = []
    for event in payload.get("events", []):
        words = "".join(s.get("utf8", "") for s in event.get("segs", []))
        if words.strip():
            result.append({"startSeconds": event.get("tStartMs", 0) / 1000,
                           "durationSeconds": event.get("dDurationMs", 0) / 1000,
                           "text": words.strip()})
    return result


def inspect(url: str, reader=fetch) -> dict:
    identity = video_id(url)
    result = {"id": identity, "url": url, "access": "unavailable", "visuallyReviewed": False,
              "metadata": None, "captions": None, "errors": []}
    try:
        data = json.loads(reader("https://www.youtube.com/oembed?" + urlencode({"url": url, "format": "json"})))
        result["metadata"] = {k: data.get(k) for k in ("title", "author_name", "author_url", "thumbnail_url")}
        result["access"] = "metadata-only"
    except Exception as error:
        # Do not log request query strings or temporary caption access URLs.
        result["errors"].append({"stage": "oembed", "type": type(error).__name__})
    try:
        player = player_json(reader(url))
        status = player.get("playabilityStatus", {})
        result["playability"] = {k: status.get(k) for k in ("status", "reason")}
        if status.get("status") != "OK":
            result["errors"].append({"stage": "watch", "type": "PlaybackUnavailable"})
            return result
        details = player.get("videoDetails", {})
        if details.get("videoId") != identity:
            raise ValueError("Player video ID does not match manifest")
        result["details"] = {k: details.get(k) for k in ("title", "author", "lengthSeconds", "shortDescription")}
        result["access"] = "metadata-only"
        tracks = player.get("captions", {}).get("playerCaptionsTracklistRenderer", {}).get("captionTracks", [])
        result["captionLanguages"] = [{"languageCode": t.get("languageCode"), "autoGenerated": t.get("kind") == "asr"} for t in tracks]
        english = [t for t in tracks if t.get("languageCode", "").startswith("en")]
        if not english:
            return result
        track = sorted(english, key=lambda t: t.get("kind") == "asr")[0]
        base = track["baseUrl"]
        safe_url(base)
        parsed = urlparse(base)
        if parsed.path != "/api/timedtext":
            raise ValueError("Unexpected public caption endpoint")
        query = parse_qs(parsed.query)
        query["fmt"] = ["json3"]
        caption_url = parsed._replace(query=urlencode(query, doseq=True)).geturl()
        events = captions_json(reader(caption_url))
        if events:
            result["captions"] = {"language": track["languageCode"], "autoGenerated": track.get("kind") == "asr", "events": events}
            result["access"] = "captions-readable"
        else:
            result["errors"].append({"stage": "captions", "type": "EmptyCaptionResponse"})
    except Exception as error:
        result["errors"].append({"stage": "watch-or-captions", "type": type(error).__name__})
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", default="references/construction-videos.json")
    parser.add_argument("--out", default="reports/reference-videos.json")
    args = parser.parse_args()
    manifest = json.loads(Path(args.manifest).read_text())
    sources = manifest["sources"]
    if not isinstance(sources, list) or not 1 <= len(sources) <= 4:
        raise ValueError("Manifest must contain 1-4 explicit sources")
    for source in sources:
        video_id(source["url"])
    if len({s["url"] for s in sources}) != len(sources):
        raise ValueError("Duplicate source")
    report = {"schemaVersion": 1, "visuallyReviewed": False, "sources": []}
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    for source in sources:
        report["sources"].append(inspect(source["url"]))
        temporary = out.with_suffix(".tmp")
        temporary.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n")
        temporary.replace(out)
    for source in report["sources"]:
        print(source["id"], source["access"], json.dumps(source.get("metadata"), ensure_ascii=False))
    # A successful runner does not mean the references were accessible/reviewed.
    return 0 if all(s["access"] == "captions-readable" for s in report["sources"]) else 2


if __name__ == "__main__":
    raise SystemExit(main())
